variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache/"

moban:
  image: python:3.5
  before_script:
    - pip install moban
    - git clone https://gitlab.com/coala/mobans ../coala-mobans
  script:
    - moban
    - git diff --exit-code

cache:
  paths:
    - .cache/pip

static_analysis:
  image: python:3.5-alpine
  script:
    - pip install 'coala-bears[alldeps]'
    - coala --ci

.common_test_script: &common_test_script
  - apk add --no-cache git
  - pip install -r requirements.txt -r test-requirements.txt
  - pytest
  - codecov

tests:3.4:
  image: python:3.4-alpine
  script: *common_test_script

tests:3.5:
  image: python:3.5-alpine
  script: *common_test_script

tests:3.6:
  image: python:3.6-alpine
  script: *common_test_script

tests:3.7:
  image: python:3.7-alpine
  script: *common_test_script
