moban:
  image: python:3.5
  before_script:
    - pip install moban
    - git clone https://github.com/moremoban/setupmobans ../setupmobans
    - git clone https://gitlab.com/coala/mobans ../coala-mobans
  script:
    - moban
    - git diff --exit-code

cache:
  paths:
    - .tox
    - ~/.local/share/coala-bears/
    - ~/.cache/pip

static_analysis:
  image: python:3.5-alpine
  script:
    - pip install 'coala-bears[alldeps]'
    - coala --ci

.common_test_script: &common_test_script
  - apk add --no-cache git
  - pip install tox~=2.7 codecov~=2.0.5
  - tox --develop
  - codecov

tests:3.4:
  image: python:3.4-alpine
  variables:
    TOXENV: py34
  script: *common_test_script

tests:3.5:
  image: python:3.5-alpine
  variables:
    TOXENV: py35
  script: *common_test_script

tests:3.6:
  image: python:3.6-alpine
  variables:
    TOXENV: py36
  script: *common_test_script
